CXX=clang++
CC=clang
CXXFLAGS=-Wall -Wextra -pedantic -std=c++23 -Og -g0 -gdwarf-5 -fsanitize=address,undefined
CFLAGS=-Wall -Wextra -pedantic -std=c2x -Oz -g0
CXXFLAGS=-Wall -Wextra -pedantic -std=c++23 -Oz -g0
LDFLAGS=-static
